/*
roverd REST API

Testing ServicesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/VU-ASE/roverctl"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_ServicesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ServicesAPIService ServicesAuthorGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var author string

		resp, httpRes, err := apiClient.ServicesAPI.ServicesAuthorGet(context.Background(), author).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicesAPIService ServicesAuthorServiceGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var author string
		var service string

		resp, httpRes, err := apiClient.ServicesAPI.ServicesAuthorServiceGet(context.Background(), author, service).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicesAPIService ServicesAuthorServiceVersionDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var author string
		var service string
		var version string

		resp, httpRes, err := apiClient.ServicesAPI.ServicesAuthorServiceVersionDelete(context.Background(), author, service, version).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicesAPIService ServicesAuthorServiceVersionGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var author string
		var service string
		var version string

		resp, httpRes, err := apiClient.ServicesAPI.ServicesAuthorServiceVersionGet(context.Background(), author, service, version).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicesAPIService ServicesAuthorServiceVersionPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var author string
		var service string
		var version string

		httpRes, err := apiClient.ServicesAPI.ServicesAuthorServiceVersionPost(context.Background(), author, service, version).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicesAPIService ServicesGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ServicesAPI.ServicesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicesAPIService ServicesPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ServicesAPI.ServicesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
