/*
roverd REST API

Testing ServicesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ServicesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ServicesAPIService ServicesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ServicesAPI.ServicesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicesAPIService ServicesNameGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string

		resp, httpRes, err := apiClient.ServicesAPI.ServicesNameGet(context.Background(), name).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicesAPIService ServicesNameVersionDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string
		var version string

		httpRes, err := apiClient.ServicesAPI.ServicesNameVersionDelete(context.Background(), name, version).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicesAPIService ServicesNameVersionGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string
		var version string

		resp, httpRes, err := apiClient.ServicesAPI.ServicesNameVersionGet(context.Background(), name, version).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicesAPIService ServicesNameVersionPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var name string
		var version string

		httpRes, err := apiClient.ServicesAPI.ServicesNameVersionPost(context.Background(), name, version).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServicesAPIService ServicesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ServicesAPI.ServicesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
