name: build and release binaries

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'

      - name: Set VERSION from tag
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build binaries for linux and macos (amd64 and arm64)
        env:
          VERSION: ${{ env.VERSION }}
        working-directory: src
        run: |
          BUILD_DIR=../bin/
          BINARY_NAME=roverctl
          LDFLAGS="-X 'github.com/VU-ASE/roverctl/src/views.version=${VERSION}'"
          mkdir -p $BUILD_DIR

          # Build for macOS Intel
          GOOS=darwin GOARCH=amd64 go build -buildvcs=false -ldflags="$LDFLAGS" -o "$BUILD_DIR${BINARY_NAME}-macos-amd64"

          # Build for macOS Silicon
          GOOS=darwin GOARCH=arm64 go build -buildvcs=false -ldflags="$LDFLAGS" -o "$BUILD_DIR${BINARY_NAME}-macos-arm64"

          # Build for Linux AMD64
          GOOS=linux GOARCH=amd64 go build -buildvcs=false -ldflags="$LDFLAGS" -o "$BUILD_DIR${BINARY_NAME}-linux-amd64"

          # Build for Linux ARM64
          GOOS=linux GOARCH=arm64 go build -buildvcs=false -ldflags="$LDFLAGS" -o "$BUILD_DIR${BINARY_NAME}-linux-arm64"

      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "bin/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ env.VERSION }}

