/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PipelineGet200ResponsePipeline type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PipelineGet200ResponsePipeline{}

// PipelineGet200ResponsePipeline struct for PipelineGet200ResponsePipeline
type PipelineGet200ResponsePipeline struct {
	Status PipelineStatus `json:"status"`
	// Milliseconds since epoch when the pipeline was manually started
	LastStart int64 `json:"last_start"`
	// Milliseconds since epoch when the pipeline was manually stopped
	LastStop int64 `json:"last_stop"`
	// Milliseconds since epoch when the pipeline was automatically restarted (on process faults)
	LastRestart int64 `json:"last_restart"`
	ValidationErrors *PipelineGet200ResponsePipelineValidationErrors `json:"validation_errors,omitempty"`
}

type _PipelineGet200ResponsePipeline PipelineGet200ResponsePipeline

// NewPipelineGet200ResponsePipeline instantiates a new PipelineGet200ResponsePipeline object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineGet200ResponsePipeline(status PipelineStatus, lastStart int64, lastStop int64, lastRestart int64) *PipelineGet200ResponsePipeline {
	this := PipelineGet200ResponsePipeline{}
	this.Status = status
	this.LastStart = lastStart
	this.LastStop = lastStop
	this.LastRestart = lastRestart
	return &this
}

// NewPipelineGet200ResponsePipelineWithDefaults instantiates a new PipelineGet200ResponsePipeline object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineGet200ResponsePipelineWithDefaults() *PipelineGet200ResponsePipeline {
	this := PipelineGet200ResponsePipeline{}
	return &this
}

// GetStatus returns the Status field value
func (o *PipelineGet200ResponsePipeline) GetStatus() PipelineStatus {
	if o == nil {
		var ret PipelineStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponsePipeline) GetStatusOk() (*PipelineStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PipelineGet200ResponsePipeline) SetStatus(v PipelineStatus) {
	o.Status = v
}

// GetLastStart returns the LastStart field value
func (o *PipelineGet200ResponsePipeline) GetLastStart() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LastStart
}

// GetLastStartOk returns a tuple with the LastStart field value
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponsePipeline) GetLastStartOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastStart, true
}

// SetLastStart sets field value
func (o *PipelineGet200ResponsePipeline) SetLastStart(v int64) {
	o.LastStart = v
}

// GetLastStop returns the LastStop field value
func (o *PipelineGet200ResponsePipeline) GetLastStop() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LastStop
}

// GetLastStopOk returns a tuple with the LastStop field value
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponsePipeline) GetLastStopOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastStop, true
}

// SetLastStop sets field value
func (o *PipelineGet200ResponsePipeline) SetLastStop(v int64) {
	o.LastStop = v
}

// GetLastRestart returns the LastRestart field value
func (o *PipelineGet200ResponsePipeline) GetLastRestart() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LastRestart
}

// GetLastRestartOk returns a tuple with the LastRestart field value
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponsePipeline) GetLastRestartOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastRestart, true
}

// SetLastRestart sets field value
func (o *PipelineGet200ResponsePipeline) SetLastRestart(v int64) {
	o.LastRestart = v
}

// GetValidationErrors returns the ValidationErrors field value if set, zero value otherwise.
func (o *PipelineGet200ResponsePipeline) GetValidationErrors() PipelineGet200ResponsePipelineValidationErrors {
	if o == nil || IsNil(o.ValidationErrors) {
		var ret PipelineGet200ResponsePipelineValidationErrors
		return ret
	}
	return *o.ValidationErrors
}

// GetValidationErrorsOk returns a tuple with the ValidationErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponsePipeline) GetValidationErrorsOk() (*PipelineGet200ResponsePipelineValidationErrors, bool) {
	if o == nil || IsNil(o.ValidationErrors) {
		return nil, false
	}
	return o.ValidationErrors, true
}

// HasValidationErrors returns a boolean if a field has been set.
func (o *PipelineGet200ResponsePipeline) HasValidationErrors() bool {
	if o != nil && !IsNil(o.ValidationErrors) {
		return true
	}

	return false
}

// SetValidationErrors gets a reference to the given PipelineGet200ResponsePipelineValidationErrors and assigns it to the ValidationErrors field.
func (o *PipelineGet200ResponsePipeline) SetValidationErrors(v PipelineGet200ResponsePipelineValidationErrors) {
	o.ValidationErrors = &v
}

func (o PipelineGet200ResponsePipeline) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PipelineGet200ResponsePipeline) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["last_start"] = o.LastStart
	toSerialize["last_stop"] = o.LastStop
	toSerialize["last_restart"] = o.LastRestart
	if !IsNil(o.ValidationErrors) {
		toSerialize["validation_errors"] = o.ValidationErrors
	}
	return toSerialize, nil
}

func (o *PipelineGet200ResponsePipeline) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"last_start",
		"last_stop",
		"last_restart",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPipelineGet200ResponsePipeline := _PipelineGet200ResponsePipeline{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPipelineGet200ResponsePipeline)

	if err != nil {
		return err
	}

	*o = PipelineGet200ResponsePipeline(varPipelineGet200ResponsePipeline)

	return err
}

type NullablePipelineGet200ResponsePipeline struct {
	value *PipelineGet200ResponsePipeline
	isSet bool
}

func (v NullablePipelineGet200ResponsePipeline) Get() *PipelineGet200ResponsePipeline {
	return v.value
}

func (v *NullablePipelineGet200ResponsePipeline) Set(val *PipelineGet200ResponsePipeline) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineGet200ResponsePipeline) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineGet200ResponsePipeline) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineGet200ResponsePipeline(val *PipelineGet200ResponsePipeline) *NullablePipelineGet200ResponsePipeline {
	return &NullablePipelineGet200ResponsePipeline{value: val, isSet: true}
}

func (v NullablePipelineGet200ResponsePipeline) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineGet200ResponsePipeline) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


