/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StatusGet200ResponseCpuInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatusGet200ResponseCpuInner{}

// StatusGet200ResponseCpuInner CPU usage information about a specific core
type StatusGet200ResponseCpuInner struct {
	// The core number
	Core int32 `json:"core"`
	// The total amount of CPU available on the core
	Total int32 `json:"total"`
	// The amount of CPU used on the core
	Used int32 `json:"used"`
}

type _StatusGet200ResponseCpuInner StatusGet200ResponseCpuInner

// NewStatusGet200ResponseCpuInner instantiates a new StatusGet200ResponseCpuInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusGet200ResponseCpuInner(core int32, total int32, used int32) *StatusGet200ResponseCpuInner {
	this := StatusGet200ResponseCpuInner{}
	this.Core = core
	this.Total = total
	this.Used = used
	return &this
}

// NewStatusGet200ResponseCpuInnerWithDefaults instantiates a new StatusGet200ResponseCpuInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusGet200ResponseCpuInnerWithDefaults() *StatusGet200ResponseCpuInner {
	this := StatusGet200ResponseCpuInner{}
	return &this
}

// GetCore returns the Core field value
func (o *StatusGet200ResponseCpuInner) GetCore() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Core
}

// GetCoreOk returns a tuple with the Core field value
// and a boolean to check if the value has been set.
func (o *StatusGet200ResponseCpuInner) GetCoreOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Core, true
}

// SetCore sets field value
func (o *StatusGet200ResponseCpuInner) SetCore(v int32) {
	o.Core = v
}

// GetTotal returns the Total field value
func (o *StatusGet200ResponseCpuInner) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *StatusGet200ResponseCpuInner) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *StatusGet200ResponseCpuInner) SetTotal(v int32) {
	o.Total = v
}

// GetUsed returns the Used field value
func (o *StatusGet200ResponseCpuInner) GetUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *StatusGet200ResponseCpuInner) GetUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *StatusGet200ResponseCpuInner) SetUsed(v int32) {
	o.Used = v
}

func (o StatusGet200ResponseCpuInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatusGet200ResponseCpuInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["core"] = o.Core
	toSerialize["total"] = o.Total
	toSerialize["used"] = o.Used
	return toSerialize, nil
}

func (o *StatusGet200ResponseCpuInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"core",
		"total",
		"used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatusGet200ResponseCpuInner := _StatusGet200ResponseCpuInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStatusGet200ResponseCpuInner)

	if err != nil {
		return err
	}

	*o = StatusGet200ResponseCpuInner(varStatusGet200ResponseCpuInner)

	return err
}

type NullableStatusGet200ResponseCpuInner struct {
	value *StatusGet200ResponseCpuInner
	isSet bool
}

func (v NullableStatusGet200ResponseCpuInner) Get() *StatusGet200ResponseCpuInner {
	return v.value
}

func (v *NullableStatusGet200ResponseCpuInner) Set(val *StatusGet200ResponseCpuInner) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusGet200ResponseCpuInner) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusGet200ResponseCpuInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusGet200ResponseCpuInner(val *StatusGet200ResponseCpuInner) *NullableStatusGet200ResponseCpuInner {
	return &NullableStatusGet200ResponseCpuInner{value: val, isSet: true}
}

func (v NullableStatusGet200ResponseCpuInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusGet200ResponseCpuInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


