/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServicesNameGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesNameGet200Response{}

// ServicesNameGet200Response struct for ServicesNameGet200Response
type ServicesNameGet200Response struct {
	// The name of the service
	Name *string `json:"name,omitempty"`
	Status *ServiceStatus `json:"status,omitempty"`
	Versions []string `json:"versions,omitempty"`
	// The version that is enabled for this service (if any)
	EnabledVersion *string `json:"enabled_version,omitempty"`
}

// NewServicesNameGet200Response instantiates a new ServicesNameGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesNameGet200Response() *ServicesNameGet200Response {
	this := ServicesNameGet200Response{}
	return &this
}

// NewServicesNameGet200ResponseWithDefaults instantiates a new ServicesNameGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesNameGet200ResponseWithDefaults() *ServicesNameGet200Response {
	this := ServicesNameGet200Response{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServicesNameGet200Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesNameGet200Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServicesNameGet200Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServicesNameGet200Response) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ServicesNameGet200Response) GetStatus() ServiceStatus {
	if o == nil || IsNil(o.Status) {
		var ret ServiceStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesNameGet200Response) GetStatusOk() (*ServiceStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ServicesNameGet200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ServiceStatus and assigns it to the Status field.
func (o *ServicesNameGet200Response) SetStatus(v ServiceStatus) {
	o.Status = &v
}

// GetVersions returns the Versions field value if set, zero value otherwise.
func (o *ServicesNameGet200Response) GetVersions() []string {
	if o == nil || IsNil(o.Versions) {
		var ret []string
		return ret
	}
	return o.Versions
}

// GetVersionsOk returns a tuple with the Versions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesNameGet200Response) GetVersionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Versions) {
		return nil, false
	}
	return o.Versions, true
}

// HasVersions returns a boolean if a field has been set.
func (o *ServicesNameGet200Response) HasVersions() bool {
	if o != nil && !IsNil(o.Versions) {
		return true
	}

	return false
}

// SetVersions gets a reference to the given []string and assigns it to the Versions field.
func (o *ServicesNameGet200Response) SetVersions(v []string) {
	o.Versions = v
}

// GetEnabledVersion returns the EnabledVersion field value if set, zero value otherwise.
func (o *ServicesNameGet200Response) GetEnabledVersion() string {
	if o == nil || IsNil(o.EnabledVersion) {
		var ret string
		return ret
	}
	return *o.EnabledVersion
}

// GetEnabledVersionOk returns a tuple with the EnabledVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesNameGet200Response) GetEnabledVersionOk() (*string, bool) {
	if o == nil || IsNil(o.EnabledVersion) {
		return nil, false
	}
	return o.EnabledVersion, true
}

// HasEnabledVersion returns a boolean if a field has been set.
func (o *ServicesNameGet200Response) HasEnabledVersion() bool {
	if o != nil && !IsNil(o.EnabledVersion) {
		return true
	}

	return false
}

// SetEnabledVersion gets a reference to the given string and assigns it to the EnabledVersion field.
func (o *ServicesNameGet200Response) SetEnabledVersion(v string) {
	o.EnabledVersion = &v
}

func (o ServicesNameGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesNameGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Versions) {
		toSerialize["versions"] = o.Versions
	}
	if !IsNil(o.EnabledVersion) {
		toSerialize["enabled_version"] = o.EnabledVersion
	}
	return toSerialize, nil
}

type NullableServicesNameGet200Response struct {
	value *ServicesNameGet200Response
	isSet bool
}

func (v NullableServicesNameGet200Response) Get() *ServicesNameGet200Response {
	return v.value
}

func (v *NullableServicesNameGet200Response) Set(val *ServicesNameGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesNameGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesNameGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesNameGet200Response(val *ServicesNameGet200Response) *NullableServicesNameGet200Response {
	return &NullableServicesNameGet200Response{value: val, isSet: true}
}

func (v NullableServicesNameGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesNameGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


