/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServicesPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesPost200Response{}

// ServicesPost200Response struct for ServicesPost200Response
type ServicesPost200Response struct {
	// The name of the service
	Name string `json:"name"`
	// The version of the service
	Version string `json:"version"`
	// The author of the service
	Author string `json:"author"`
	// Whether the pipeline was invalidated by this service upload
	InvalidatedPipeline bool `json:"invalidated_pipeline"`
}

type _ServicesPost200Response ServicesPost200Response

// NewServicesPost200Response instantiates a new ServicesPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesPost200Response(name string, version string, author string, invalidatedPipeline bool) *ServicesPost200Response {
	this := ServicesPost200Response{}
	this.Name = name
	this.Version = version
	this.Author = author
	this.InvalidatedPipeline = invalidatedPipeline
	return &this
}

// NewServicesPost200ResponseWithDefaults instantiates a new ServicesPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesPost200ResponseWithDefaults() *ServicesPost200Response {
	this := ServicesPost200Response{}
	return &this
}

// GetName returns the Name field value
func (o *ServicesPost200Response) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServicesPost200Response) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServicesPost200Response) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *ServicesPost200Response) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *ServicesPost200Response) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *ServicesPost200Response) SetVersion(v string) {
	o.Version = v
}

// GetAuthor returns the Author field value
func (o *ServicesPost200Response) GetAuthor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *ServicesPost200Response) GetAuthorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *ServicesPost200Response) SetAuthor(v string) {
	o.Author = v
}

// GetInvalidatedPipeline returns the InvalidatedPipeline field value
func (o *ServicesPost200Response) GetInvalidatedPipeline() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.InvalidatedPipeline
}

// GetInvalidatedPipelineOk returns a tuple with the InvalidatedPipeline field value
// and a boolean to check if the value has been set.
func (o *ServicesPost200Response) GetInvalidatedPipelineOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvalidatedPipeline, true
}

// SetInvalidatedPipeline sets field value
func (o *ServicesPost200Response) SetInvalidatedPipeline(v bool) {
	o.InvalidatedPipeline = v
}

func (o ServicesPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	toSerialize["author"] = o.Author
	toSerialize["invalidated_pipeline"] = o.InvalidatedPipeline
	return toSerialize, nil
}

func (o *ServicesPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"version",
		"author",
		"invalidated_pipeline",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServicesPost200Response := _ServicesPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServicesPost200Response)

	if err != nil {
		return err
	}

	*o = ServicesPost200Response(varServicesPost200Response)

	return err
}

type NullableServicesPost200Response struct {
	value *ServicesPost200Response
	isSet bool
}

func (v NullableServicesPost200Response) Get() *ServicesPost200Response {
	return v.value
}

func (v *NullableServicesPost200Response) Set(val *ServicesPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesPost200Response(val *ServicesPost200Response) *NullableServicesPost200Response {
	return &NullableServicesPost200Response{value: val, isSet: true}
}

func (v NullableServicesPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


