/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServicesAuthorServiceVersionPost400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesAuthorServiceVersionPost400Response{}

// ServicesAuthorServiceVersionPost400Response struct for ServicesAuthorServiceVersionPost400Response
type ServicesAuthorServiceVersionPost400Response struct {
	// The error message
	Message string `json:"message"`
	// The build log (one log line per item)
	BuildLog []string `json:"build_log,omitempty"`
}

type _ServicesAuthorServiceVersionPost400Response ServicesAuthorServiceVersionPost400Response

// NewServicesAuthorServiceVersionPost400Response instantiates a new ServicesAuthorServiceVersionPost400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesAuthorServiceVersionPost400Response(message string) *ServicesAuthorServiceVersionPost400Response {
	this := ServicesAuthorServiceVersionPost400Response{}
	this.Message = message
	return &this
}

// NewServicesAuthorServiceVersionPost400ResponseWithDefaults instantiates a new ServicesAuthorServiceVersionPost400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesAuthorServiceVersionPost400ResponseWithDefaults() *ServicesAuthorServiceVersionPost400Response {
	this := ServicesAuthorServiceVersionPost400Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *ServicesAuthorServiceVersionPost400Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ServicesAuthorServiceVersionPost400Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ServicesAuthorServiceVersionPost400Response) SetMessage(v string) {
	o.Message = v
}

// GetBuildLog returns the BuildLog field value if set, zero value otherwise.
func (o *ServicesAuthorServiceVersionPost400Response) GetBuildLog() []string {
	if o == nil || IsNil(o.BuildLog) {
		var ret []string
		return ret
	}
	return o.BuildLog
}

// GetBuildLogOk returns a tuple with the BuildLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesAuthorServiceVersionPost400Response) GetBuildLogOk() ([]string, bool) {
	if o == nil || IsNil(o.BuildLog) {
		return nil, false
	}
	return o.BuildLog, true
}

// HasBuildLog returns a boolean if a field has been set.
func (o *ServicesAuthorServiceVersionPost400Response) HasBuildLog() bool {
	if o != nil && !IsNil(o.BuildLog) {
		return true
	}

	return false
}

// SetBuildLog gets a reference to the given []string and assigns it to the BuildLog field.
func (o *ServicesAuthorServiceVersionPost400Response) SetBuildLog(v []string) {
	o.BuildLog = v
}

func (o ServicesAuthorServiceVersionPost400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesAuthorServiceVersionPost400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	if !IsNil(o.BuildLog) {
		toSerialize["build_log"] = o.BuildLog
	}
	return toSerialize, nil
}

func (o *ServicesAuthorServiceVersionPost400Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServicesAuthorServiceVersionPost400Response := _ServicesAuthorServiceVersionPost400Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServicesAuthorServiceVersionPost400Response)

	if err != nil {
		return err
	}

	*o = ServicesAuthorServiceVersionPost400Response(varServicesAuthorServiceVersionPost400Response)

	return err
}

type NullableServicesAuthorServiceVersionPost400Response struct {
	value *ServicesAuthorServiceVersionPost400Response
	isSet bool
}

func (v NullableServicesAuthorServiceVersionPost400Response) Get() *ServicesAuthorServiceVersionPost400Response {
	return v.value
}

func (v *NullableServicesAuthorServiceVersionPost400Response) Set(val *ServicesAuthorServiceVersionPost400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesAuthorServiceVersionPost400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesAuthorServiceVersionPost400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesAuthorServiceVersionPost400Response(val *ServicesAuthorServiceVersionPost400Response) *NullableServicesAuthorServiceVersionPost400Response {
	return &NullableServicesAuthorServiceVersionPost400Response{value: val, isSet: true}
}

func (v NullableServicesAuthorServiceVersionPost400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesAuthorServiceVersionPost400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


