/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PipelineGet200ResponseEnabledInnerService type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PipelineGet200ResponseEnabledInnerService{}

// PipelineGet200ResponseEnabledInnerService The fully qualified service that is enabled
type PipelineGet200ResponseEnabledInnerService struct {
	// The name of the service
	Name string `json:"name"`
	// The version of the service
	Version string `json:"version"`
	// The author of the service
	Author string `json:"author"`
	// The number of faults that have occurred (causing the pipeline to restart) since pipeline.last_start
	Faults int32 `json:"faults"`
	// The most recent exit code returned by the process.
	Exit int32 `json:"exit"`
}

type _PipelineGet200ResponseEnabledInnerService PipelineGet200ResponseEnabledInnerService

// NewPipelineGet200ResponseEnabledInnerService instantiates a new PipelineGet200ResponseEnabledInnerService object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineGet200ResponseEnabledInnerService(name string, version string, author string, faults int32, exit int32) *PipelineGet200ResponseEnabledInnerService {
	this := PipelineGet200ResponseEnabledInnerService{}
	this.Name = name
	this.Version = version
	this.Author = author
	this.Faults = faults
	this.Exit = exit
	return &this
}

// NewPipelineGet200ResponseEnabledInnerServiceWithDefaults instantiates a new PipelineGet200ResponseEnabledInnerService object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineGet200ResponseEnabledInnerServiceWithDefaults() *PipelineGet200ResponseEnabledInnerService {
	this := PipelineGet200ResponseEnabledInnerService{}
	return &this
}

// GetName returns the Name field value
func (o *PipelineGet200ResponseEnabledInnerService) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponseEnabledInnerService) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PipelineGet200ResponseEnabledInnerService) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *PipelineGet200ResponseEnabledInnerService) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponseEnabledInnerService) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *PipelineGet200ResponseEnabledInnerService) SetVersion(v string) {
	o.Version = v
}

// GetAuthor returns the Author field value
func (o *PipelineGet200ResponseEnabledInnerService) GetAuthor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponseEnabledInnerService) GetAuthorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *PipelineGet200ResponseEnabledInnerService) SetAuthor(v string) {
	o.Author = v
}

// GetFaults returns the Faults field value
func (o *PipelineGet200ResponseEnabledInnerService) GetFaults() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Faults
}

// GetFaultsOk returns a tuple with the Faults field value
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponseEnabledInnerService) GetFaultsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Faults, true
}

// SetFaults sets field value
func (o *PipelineGet200ResponseEnabledInnerService) SetFaults(v int32) {
	o.Faults = v
}

// GetExit returns the Exit field value
func (o *PipelineGet200ResponseEnabledInnerService) GetExit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Exit
}

// GetExitOk returns a tuple with the Exit field value
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponseEnabledInnerService) GetExitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Exit, true
}

// SetExit sets field value
func (o *PipelineGet200ResponseEnabledInnerService) SetExit(v int32) {
	o.Exit = v
}

func (o PipelineGet200ResponseEnabledInnerService) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PipelineGet200ResponseEnabledInnerService) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	toSerialize["author"] = o.Author
	toSerialize["faults"] = o.Faults
	toSerialize["exit"] = o.Exit
	return toSerialize, nil
}

func (o *PipelineGet200ResponseEnabledInnerService) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"version",
		"author",
		"faults",
		"exit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPipelineGet200ResponseEnabledInnerService := _PipelineGet200ResponseEnabledInnerService{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPipelineGet200ResponseEnabledInnerService)

	if err != nil {
		return err
	}

	*o = PipelineGet200ResponseEnabledInnerService(varPipelineGet200ResponseEnabledInnerService)

	return err
}

type NullablePipelineGet200ResponseEnabledInnerService struct {
	value *PipelineGet200ResponseEnabledInnerService
	isSet bool
}

func (v NullablePipelineGet200ResponseEnabledInnerService) Get() *PipelineGet200ResponseEnabledInnerService {
	return v.value
}

func (v *NullablePipelineGet200ResponseEnabledInnerService) Set(val *PipelineGet200ResponseEnabledInnerService) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineGet200ResponseEnabledInnerService) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineGet200ResponseEnabledInnerService) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineGet200ResponseEnabledInnerService(val *PipelineGet200ResponseEnabledInnerService) *NullablePipelineGet200ResponseEnabledInnerService {
	return &NullablePipelineGet200ResponseEnabledInnerService{value: val, isSet: true}
}

func (v NullablePipelineGet200ResponseEnabledInnerService) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineGet200ResponseEnabledInnerService) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


