/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PipelineGet200ResponsePipeline type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PipelineGet200ResponsePipeline{}

// PipelineGet200ResponsePipeline struct for PipelineGet200ResponsePipeline
type PipelineGet200ResponsePipeline struct {
	Status *PipelineStatus `json:"status,omitempty"`
	// Milliseconds since epoch when the pipeline was manually started
	LastStart *int64 `json:"last_start,omitempty"`
	// Milliseconds since epoch when the pipeline was manually stopped
	LastStop *int64 `json:"last_stop,omitempty"`
	// Milliseconds since epoch when the pipeline was automatically restarted (on process faults)
	LastRestart *int64 `json:"last_restart,omitempty"`
}

// NewPipelineGet200ResponsePipeline instantiates a new PipelineGet200ResponsePipeline object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineGet200ResponsePipeline() *PipelineGet200ResponsePipeline {
	this := PipelineGet200ResponsePipeline{}
	return &this
}

// NewPipelineGet200ResponsePipelineWithDefaults instantiates a new PipelineGet200ResponsePipeline object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineGet200ResponsePipelineWithDefaults() *PipelineGet200ResponsePipeline {
	this := PipelineGet200ResponsePipeline{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PipelineGet200ResponsePipeline) GetStatus() PipelineStatus {
	if o == nil || IsNil(o.Status) {
		var ret PipelineStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponsePipeline) GetStatusOk() (*PipelineStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PipelineGet200ResponsePipeline) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given PipelineStatus and assigns it to the Status field.
func (o *PipelineGet200ResponsePipeline) SetStatus(v PipelineStatus) {
	o.Status = &v
}

// GetLastStart returns the LastStart field value if set, zero value otherwise.
func (o *PipelineGet200ResponsePipeline) GetLastStart() int64 {
	if o == nil || IsNil(o.LastStart) {
		var ret int64
		return ret
	}
	return *o.LastStart
}

// GetLastStartOk returns a tuple with the LastStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponsePipeline) GetLastStartOk() (*int64, bool) {
	if o == nil || IsNil(o.LastStart) {
		return nil, false
	}
	return o.LastStart, true
}

// HasLastStart returns a boolean if a field has been set.
func (o *PipelineGet200ResponsePipeline) HasLastStart() bool {
	if o != nil && !IsNil(o.LastStart) {
		return true
	}

	return false
}

// SetLastStart gets a reference to the given int64 and assigns it to the LastStart field.
func (o *PipelineGet200ResponsePipeline) SetLastStart(v int64) {
	o.LastStart = &v
}

// GetLastStop returns the LastStop field value if set, zero value otherwise.
func (o *PipelineGet200ResponsePipeline) GetLastStop() int64 {
	if o == nil || IsNil(o.LastStop) {
		var ret int64
		return ret
	}
	return *o.LastStop
}

// GetLastStopOk returns a tuple with the LastStop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponsePipeline) GetLastStopOk() (*int64, bool) {
	if o == nil || IsNil(o.LastStop) {
		return nil, false
	}
	return o.LastStop, true
}

// HasLastStop returns a boolean if a field has been set.
func (o *PipelineGet200ResponsePipeline) HasLastStop() bool {
	if o != nil && !IsNil(o.LastStop) {
		return true
	}

	return false
}

// SetLastStop gets a reference to the given int64 and assigns it to the LastStop field.
func (o *PipelineGet200ResponsePipeline) SetLastStop(v int64) {
	o.LastStop = &v
}

// GetLastRestart returns the LastRestart field value if set, zero value otherwise.
func (o *PipelineGet200ResponsePipeline) GetLastRestart() int64 {
	if o == nil || IsNil(o.LastRestart) {
		var ret int64
		return ret
	}
	return *o.LastRestart
}

// GetLastRestartOk returns a tuple with the LastRestart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponsePipeline) GetLastRestartOk() (*int64, bool) {
	if o == nil || IsNil(o.LastRestart) {
		return nil, false
	}
	return o.LastRestart, true
}

// HasLastRestart returns a boolean if a field has been set.
func (o *PipelineGet200ResponsePipeline) HasLastRestart() bool {
	if o != nil && !IsNil(o.LastRestart) {
		return true
	}

	return false
}

// SetLastRestart gets a reference to the given int64 and assigns it to the LastRestart field.
func (o *PipelineGet200ResponsePipeline) SetLastRestart(v int64) {
	o.LastRestart = &v
}

func (o PipelineGet200ResponsePipeline) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PipelineGet200ResponsePipeline) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.LastStart) {
		toSerialize["last_start"] = o.LastStart
	}
	if !IsNil(o.LastStop) {
		toSerialize["last_stop"] = o.LastStop
	}
	if !IsNil(o.LastRestart) {
		toSerialize["last_restart"] = o.LastRestart
	}
	return toSerialize, nil
}

type NullablePipelineGet200ResponsePipeline struct {
	value *PipelineGet200ResponsePipeline
	isSet bool
}

func (v NullablePipelineGet200ResponsePipeline) Get() *PipelineGet200ResponsePipeline {
	return v.value
}

func (v *NullablePipelineGet200ResponsePipeline) Set(val *PipelineGet200ResponsePipeline) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineGet200ResponsePipeline) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineGet200ResponsePipeline) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineGet200ResponsePipeline(val *PipelineGet200ResponsePipeline) *NullablePipelineGet200ResponsePipeline {
	return &NullablePipelineGet200ResponsePipeline{value: val, isSet: true}
}

func (v NullablePipelineGet200ResponsePipeline) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineGet200ResponsePipeline) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


