/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServicesAuthorServiceVersionGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesAuthorServiceVersionGet200Response{}

// ServicesAuthorServiceVersionGet200Response struct for ServicesAuthorServiceVersionGet200Response
type ServicesAuthorServiceVersionGet200Response struct {
	// The time this version was last built as milliseconds since epoch, not set if the service was never built
	BuiltAt *int64 `json:"built_at,omitempty"`
	// The dependencies/inputs of this service version
	Inputs []ServicesAuthorServiceVersionGet200ResponseInputsInner `json:"inputs"`
	// The output streams of this service version
	Outputs []string `json:"outputs"`
	// All configuration values of this service version and their tunability
	Configuration []ServicesAuthorServiceVersionGet200ResponseConfigurationInner `json:"configuration"`
}

type _ServicesAuthorServiceVersionGet200Response ServicesAuthorServiceVersionGet200Response

// NewServicesAuthorServiceVersionGet200Response instantiates a new ServicesAuthorServiceVersionGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesAuthorServiceVersionGet200Response(inputs []ServicesAuthorServiceVersionGet200ResponseInputsInner, outputs []string, configuration []ServicesAuthorServiceVersionGet200ResponseConfigurationInner) *ServicesAuthorServiceVersionGet200Response {
	this := ServicesAuthorServiceVersionGet200Response{}
	this.Inputs = inputs
	this.Outputs = outputs
	this.Configuration = configuration
	return &this
}

// NewServicesAuthorServiceVersionGet200ResponseWithDefaults instantiates a new ServicesAuthorServiceVersionGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesAuthorServiceVersionGet200ResponseWithDefaults() *ServicesAuthorServiceVersionGet200Response {
	this := ServicesAuthorServiceVersionGet200Response{}
	return &this
}

// GetBuiltAt returns the BuiltAt field value if set, zero value otherwise.
func (o *ServicesAuthorServiceVersionGet200Response) GetBuiltAt() int64 {
	if o == nil || IsNil(o.BuiltAt) {
		var ret int64
		return ret
	}
	return *o.BuiltAt
}

// GetBuiltAtOk returns a tuple with the BuiltAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesAuthorServiceVersionGet200Response) GetBuiltAtOk() (*int64, bool) {
	if o == nil || IsNil(o.BuiltAt) {
		return nil, false
	}
	return o.BuiltAt, true
}

// HasBuiltAt returns a boolean if a field has been set.
func (o *ServicesAuthorServiceVersionGet200Response) HasBuiltAt() bool {
	if o != nil && !IsNil(o.BuiltAt) {
		return true
	}

	return false
}

// SetBuiltAt gets a reference to the given int64 and assigns it to the BuiltAt field.
func (o *ServicesAuthorServiceVersionGet200Response) SetBuiltAt(v int64) {
	o.BuiltAt = &v
}

// GetInputs returns the Inputs field value
func (o *ServicesAuthorServiceVersionGet200Response) GetInputs() []ServicesAuthorServiceVersionGet200ResponseInputsInner {
	if o == nil {
		var ret []ServicesAuthorServiceVersionGet200ResponseInputsInner
		return ret
	}

	return o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value
// and a boolean to check if the value has been set.
func (o *ServicesAuthorServiceVersionGet200Response) GetInputsOk() ([]ServicesAuthorServiceVersionGet200ResponseInputsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Inputs, true
}

// SetInputs sets field value
func (o *ServicesAuthorServiceVersionGet200Response) SetInputs(v []ServicesAuthorServiceVersionGet200ResponseInputsInner) {
	o.Inputs = v
}

// GetOutputs returns the Outputs field value
func (o *ServicesAuthorServiceVersionGet200Response) GetOutputs() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Outputs
}

// GetOutputsOk returns a tuple with the Outputs field value
// and a boolean to check if the value has been set.
func (o *ServicesAuthorServiceVersionGet200Response) GetOutputsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Outputs, true
}

// SetOutputs sets field value
func (o *ServicesAuthorServiceVersionGet200Response) SetOutputs(v []string) {
	o.Outputs = v
}

// GetConfiguration returns the Configuration field value
func (o *ServicesAuthorServiceVersionGet200Response) GetConfiguration() []ServicesAuthorServiceVersionGet200ResponseConfigurationInner {
	if o == nil {
		var ret []ServicesAuthorServiceVersionGet200ResponseConfigurationInner
		return ret
	}

	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value
// and a boolean to check if the value has been set.
func (o *ServicesAuthorServiceVersionGet200Response) GetConfigurationOk() ([]ServicesAuthorServiceVersionGet200ResponseConfigurationInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Configuration, true
}

// SetConfiguration sets field value
func (o *ServicesAuthorServiceVersionGet200Response) SetConfiguration(v []ServicesAuthorServiceVersionGet200ResponseConfigurationInner) {
	o.Configuration = v
}

func (o ServicesAuthorServiceVersionGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesAuthorServiceVersionGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BuiltAt) {
		toSerialize["built_at"] = o.BuiltAt
	}
	toSerialize["inputs"] = o.Inputs
	toSerialize["outputs"] = o.Outputs
	toSerialize["configuration"] = o.Configuration
	return toSerialize, nil
}

func (o *ServicesAuthorServiceVersionGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"inputs",
		"outputs",
		"configuration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServicesAuthorServiceVersionGet200Response := _ServicesAuthorServiceVersionGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServicesAuthorServiceVersionGet200Response)

	if err != nil {
		return err
	}

	*o = ServicesAuthorServiceVersionGet200Response(varServicesAuthorServiceVersionGet200Response)

	return err
}

type NullableServicesAuthorServiceVersionGet200Response struct {
	value *ServicesAuthorServiceVersionGet200Response
	isSet bool
}

func (v NullableServicesAuthorServiceVersionGet200Response) Get() *ServicesAuthorServiceVersionGet200Response {
	return v.value
}

func (v *NullableServicesAuthorServiceVersionGet200Response) Set(val *ServicesAuthorServiceVersionGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesAuthorServiceVersionGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesAuthorServiceVersionGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesAuthorServiceVersionGet200Response(val *ServicesAuthorServiceVersionGet200Response) *NullableServicesAuthorServiceVersionGet200Response {
	return &NullableServicesAuthorServiceVersionGet200Response{value: val, isSet: true}
}

func (v NullableServicesAuthorServiceVersionGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesAuthorServiceVersionGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


