/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PipelineGet200ResponseProcessesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PipelineGet200ResponseProcessesInner{}

// PipelineGet200ResponseProcessesInner struct for PipelineGet200ResponseProcessesInner
type PipelineGet200ResponseProcessesInner struct {
	// The name of the service running as a process
	Name *string `json:"name,omitempty"`
	Status *ProcessStatus `json:"status,omitempty"`
	// The process ID
	Pid *int32 `json:"pid,omitempty"`
	// The number of milliseconds the process has been running
	Uptime *int64 `json:"uptime,omitempty"`
	// The amount of memory used by the process in megabytes
	Memory *int32 `json:"memory,omitempty"`
	// The percentage of CPU used by the process
	Cpu *int32 `json:"cpu,omitempty"`
	// The number of faults that have occurred (causing the pipeline to restart) since last_start
	Faults *int32 `json:"faults,omitempty"`
}

// NewPipelineGet200ResponseProcessesInner instantiates a new PipelineGet200ResponseProcessesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineGet200ResponseProcessesInner() *PipelineGet200ResponseProcessesInner {
	this := PipelineGet200ResponseProcessesInner{}
	return &this
}

// NewPipelineGet200ResponseProcessesInnerWithDefaults instantiates a new PipelineGet200ResponseProcessesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineGet200ResponseProcessesInnerWithDefaults() *PipelineGet200ResponseProcessesInner {
	this := PipelineGet200ResponseProcessesInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PipelineGet200ResponseProcessesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponseProcessesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PipelineGet200ResponseProcessesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PipelineGet200ResponseProcessesInner) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PipelineGet200ResponseProcessesInner) GetStatus() ProcessStatus {
	if o == nil || IsNil(o.Status) {
		var ret ProcessStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponseProcessesInner) GetStatusOk() (*ProcessStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PipelineGet200ResponseProcessesInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ProcessStatus and assigns it to the Status field.
func (o *PipelineGet200ResponseProcessesInner) SetStatus(v ProcessStatus) {
	o.Status = &v
}

// GetPid returns the Pid field value if set, zero value otherwise.
func (o *PipelineGet200ResponseProcessesInner) GetPid() int32 {
	if o == nil || IsNil(o.Pid) {
		var ret int32
		return ret
	}
	return *o.Pid
}

// GetPidOk returns a tuple with the Pid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponseProcessesInner) GetPidOk() (*int32, bool) {
	if o == nil || IsNil(o.Pid) {
		return nil, false
	}
	return o.Pid, true
}

// HasPid returns a boolean if a field has been set.
func (o *PipelineGet200ResponseProcessesInner) HasPid() bool {
	if o != nil && !IsNil(o.Pid) {
		return true
	}

	return false
}

// SetPid gets a reference to the given int32 and assigns it to the Pid field.
func (o *PipelineGet200ResponseProcessesInner) SetPid(v int32) {
	o.Pid = &v
}

// GetUptime returns the Uptime field value if set, zero value otherwise.
func (o *PipelineGet200ResponseProcessesInner) GetUptime() int64 {
	if o == nil || IsNil(o.Uptime) {
		var ret int64
		return ret
	}
	return *o.Uptime
}

// GetUptimeOk returns a tuple with the Uptime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponseProcessesInner) GetUptimeOk() (*int64, bool) {
	if o == nil || IsNil(o.Uptime) {
		return nil, false
	}
	return o.Uptime, true
}

// HasUptime returns a boolean if a field has been set.
func (o *PipelineGet200ResponseProcessesInner) HasUptime() bool {
	if o != nil && !IsNil(o.Uptime) {
		return true
	}

	return false
}

// SetUptime gets a reference to the given int64 and assigns it to the Uptime field.
func (o *PipelineGet200ResponseProcessesInner) SetUptime(v int64) {
	o.Uptime = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *PipelineGet200ResponseProcessesInner) GetMemory() int32 {
	if o == nil || IsNil(o.Memory) {
		var ret int32
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponseProcessesInner) GetMemoryOk() (*int32, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *PipelineGet200ResponseProcessesInner) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given int32 and assigns it to the Memory field.
func (o *PipelineGet200ResponseProcessesInner) SetMemory(v int32) {
	o.Memory = &v
}

// GetCpu returns the Cpu field value if set, zero value otherwise.
func (o *PipelineGet200ResponseProcessesInner) GetCpu() int32 {
	if o == nil || IsNil(o.Cpu) {
		var ret int32
		return ret
	}
	return *o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponseProcessesInner) GetCpuOk() (*int32, bool) {
	if o == nil || IsNil(o.Cpu) {
		return nil, false
	}
	return o.Cpu, true
}

// HasCpu returns a boolean if a field has been set.
func (o *PipelineGet200ResponseProcessesInner) HasCpu() bool {
	if o != nil && !IsNil(o.Cpu) {
		return true
	}

	return false
}

// SetCpu gets a reference to the given int32 and assigns it to the Cpu field.
func (o *PipelineGet200ResponseProcessesInner) SetCpu(v int32) {
	o.Cpu = &v
}

// GetFaults returns the Faults field value if set, zero value otherwise.
func (o *PipelineGet200ResponseProcessesInner) GetFaults() int32 {
	if o == nil || IsNil(o.Faults) {
		var ret int32
		return ret
	}
	return *o.Faults
}

// GetFaultsOk returns a tuple with the Faults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineGet200ResponseProcessesInner) GetFaultsOk() (*int32, bool) {
	if o == nil || IsNil(o.Faults) {
		return nil, false
	}
	return o.Faults, true
}

// HasFaults returns a boolean if a field has been set.
func (o *PipelineGet200ResponseProcessesInner) HasFaults() bool {
	if o != nil && !IsNil(o.Faults) {
		return true
	}

	return false
}

// SetFaults gets a reference to the given int32 and assigns it to the Faults field.
func (o *PipelineGet200ResponseProcessesInner) SetFaults(v int32) {
	o.Faults = &v
}

func (o PipelineGet200ResponseProcessesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PipelineGet200ResponseProcessesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Pid) {
		toSerialize["pid"] = o.Pid
	}
	if !IsNil(o.Uptime) {
		toSerialize["uptime"] = o.Uptime
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.Cpu) {
		toSerialize["cpu"] = o.Cpu
	}
	if !IsNil(o.Faults) {
		toSerialize["faults"] = o.Faults
	}
	return toSerialize, nil
}

type NullablePipelineGet200ResponseProcessesInner struct {
	value *PipelineGet200ResponseProcessesInner
	isSet bool
}

func (v NullablePipelineGet200ResponseProcessesInner) Get() *PipelineGet200ResponseProcessesInner {
	return v.value
}

func (v *NullablePipelineGet200ResponseProcessesInner) Set(val *PipelineGet200ResponseProcessesInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineGet200ResponseProcessesInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineGet200ResponseProcessesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineGet200ResponseProcessesInner(val *PipelineGet200ResponseProcessesInner) *NullablePipelineGet200ResponseProcessesInner {
	return &NullablePipelineGet200ResponseProcessesInner{value: val, isSet: true}
}

func (v NullablePipelineGet200ResponseProcessesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineGet200ResponseProcessesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


