/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServicesPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesPost200Response{}

// ServicesPost200Response struct for ServicesPost200Response
type ServicesPost200Response struct {
	// The name of the service
	Name *string `json:"name,omitempty"`
	// The version of the service
	Version *string `json:"version,omitempty"`
}

// NewServicesPost200Response instantiates a new ServicesPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesPost200Response() *ServicesPost200Response {
	this := ServicesPost200Response{}
	return &this
}

// NewServicesPost200ResponseWithDefaults instantiates a new ServicesPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesPost200ResponseWithDefaults() *ServicesPost200Response {
	this := ServicesPost200Response{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServicesPost200Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesPost200Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServicesPost200Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServicesPost200Response) SetName(v string) {
	o.Name = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ServicesPost200Response) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesPost200Response) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ServicesPost200Response) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ServicesPost200Response) SetVersion(v string) {
	o.Version = &v
}

func (o ServicesPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableServicesPost200Response struct {
	value *ServicesPost200Response
	isSet bool
}

func (v NullableServicesPost200Response) Get() *ServicesPost200Response {
	return v.value
}

func (v *NullableServicesPost200Response) Set(val *ServicesPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesPost200Response(val *ServicesPost200Response) *NullableServicesPost200Response {
	return &NullableServicesPost200Response{value: val, isSet: true}
}

func (v NullableServicesPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


