/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SourcesPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourcesPostRequest{}

// SourcesPostRequest struct for SourcesPostRequest
type SourcesPostRequest struct {
	// The name of the source
	Name *string `json:"name,omitempty"`
	// The URL of the source (without scheme)
	Url *string `json:"url,omitempty"`
	// The version of the source
	Version *string `json:"version,omitempty"`
}

// NewSourcesPostRequest instantiates a new SourcesPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourcesPostRequest() *SourcesPostRequest {
	this := SourcesPostRequest{}
	return &this
}

// NewSourcesPostRequestWithDefaults instantiates a new SourcesPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourcesPostRequestWithDefaults() *SourcesPostRequest {
	this := SourcesPostRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SourcesPostRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourcesPostRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SourcesPostRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SourcesPostRequest) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *SourcesPostRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourcesPostRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *SourcesPostRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *SourcesPostRequest) SetUrl(v string) {
	o.Url = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *SourcesPostRequest) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SourcesPostRequest) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *SourcesPostRequest) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *SourcesPostRequest) SetVersion(v string) {
	o.Version = &v
}

func (o SourcesPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourcesPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableSourcesPostRequest struct {
	value *SourcesPostRequest
	isSet bool
}

func (v NullableSourcesPostRequest) Get() *SourcesPostRequest {
	return v.value
}

func (v *NullableSourcesPostRequest) Set(val *SourcesPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSourcesPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSourcesPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourcesPostRequest(val *SourcesPostRequest) *NullableSourcesPostRequest {
	return &NullableSourcesPostRequest{value: val, isSet: true}
}

func (v NullableSourcesPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourcesPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


