/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServicesGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesGet200ResponseInner{}

// ServicesGet200ResponseInner struct for ServicesGet200ResponseInner
type ServicesGet200ResponseInner struct {
	// The name of the service
	Name *string `json:"name,omitempty"`
	Status *ServiceStatus `json:"status,omitempty"`
	// The version that is enabled for this service (if any)
	EnabledVersion *string `json:"enabled_version,omitempty"`
}

// NewServicesGet200ResponseInner instantiates a new ServicesGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesGet200ResponseInner() *ServicesGet200ResponseInner {
	this := ServicesGet200ResponseInner{}
	return &this
}

// NewServicesGet200ResponseInnerWithDefaults instantiates a new ServicesGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesGet200ResponseInnerWithDefaults() *ServicesGet200ResponseInner {
	this := ServicesGet200ResponseInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServicesGet200ResponseInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesGet200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServicesGet200ResponseInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServicesGet200ResponseInner) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ServicesGet200ResponseInner) GetStatus() ServiceStatus {
	if o == nil || IsNil(o.Status) {
		var ret ServiceStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesGet200ResponseInner) GetStatusOk() (*ServiceStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ServicesGet200ResponseInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ServiceStatus and assigns it to the Status field.
func (o *ServicesGet200ResponseInner) SetStatus(v ServiceStatus) {
	o.Status = &v
}

// GetEnabledVersion returns the EnabledVersion field value if set, zero value otherwise.
func (o *ServicesGet200ResponseInner) GetEnabledVersion() string {
	if o == nil || IsNil(o.EnabledVersion) {
		var ret string
		return ret
	}
	return *o.EnabledVersion
}

// GetEnabledVersionOk returns a tuple with the EnabledVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesGet200ResponseInner) GetEnabledVersionOk() (*string, bool) {
	if o == nil || IsNil(o.EnabledVersion) {
		return nil, false
	}
	return o.EnabledVersion, true
}

// HasEnabledVersion returns a boolean if a field has been set.
func (o *ServicesGet200ResponseInner) HasEnabledVersion() bool {
	if o != nil && !IsNil(o.EnabledVersion) {
		return true
	}

	return false
}

// SetEnabledVersion gets a reference to the given string and assigns it to the EnabledVersion field.
func (o *ServicesGet200ResponseInner) SetEnabledVersion(v string) {
	o.EnabledVersion = &v
}

func (o ServicesGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.EnabledVersion) {
		toSerialize["enabled_version"] = o.EnabledVersion
	}
	return toSerialize, nil
}

type NullableServicesGet200ResponseInner struct {
	value *ServicesGet200ResponseInner
	isSet bool
}

func (v NullableServicesGet200ResponseInner) Get() *ServicesGet200ResponseInner {
	return v.value
}

func (v *NullableServicesGet200ResponseInner) Set(val *ServicesGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesGet200ResponseInner(val *ServicesGet200ResponseInner) *NullableServicesGet200ResponseInner {
	return &NullableServicesGet200ResponseInner{value: val, isSet: true}
}

func (v NullableServicesGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


