/*
roverd REST API

API exposed from each rover to allow process, service, source and file management

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PipelinePostRequestInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PipelinePostRequestInner{}

// PipelinePostRequestInner struct for PipelinePostRequestInner
type PipelinePostRequestInner struct {
	// The name of the service
	Name string `json:"name"`
	// The version of the service
	Version string `json:"version"`
	// The author of the service
	Author string `json:"author"`
}

type _PipelinePostRequestInner PipelinePostRequestInner

// NewPipelinePostRequestInner instantiates a new PipelinePostRequestInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelinePostRequestInner(name string, version string, author string) *PipelinePostRequestInner {
	this := PipelinePostRequestInner{}
	this.Name = name
	this.Version = version
	this.Author = author
	return &this
}

// NewPipelinePostRequestInnerWithDefaults instantiates a new PipelinePostRequestInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelinePostRequestInnerWithDefaults() *PipelinePostRequestInner {
	this := PipelinePostRequestInner{}
	return &this
}

// GetName returns the Name field value
func (o *PipelinePostRequestInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PipelinePostRequestInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PipelinePostRequestInner) SetName(v string) {
	o.Name = v
}

// GetVersion returns the Version field value
func (o *PipelinePostRequestInner) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *PipelinePostRequestInner) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *PipelinePostRequestInner) SetVersion(v string) {
	o.Version = v
}

// GetAuthor returns the Author field value
func (o *PipelinePostRequestInner) GetAuthor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Author
}

// GetAuthorOk returns a tuple with the Author field value
// and a boolean to check if the value has been set.
func (o *PipelinePostRequestInner) GetAuthorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Author, true
}

// SetAuthor sets field value
func (o *PipelinePostRequestInner) SetAuthor(v string) {
	o.Author = v
}

func (o PipelinePostRequestInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PipelinePostRequestInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["version"] = o.Version
	toSerialize["author"] = o.Author
	return toSerialize, nil
}

func (o *PipelinePostRequestInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"version",
		"author",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPipelinePostRequestInner := _PipelinePostRequestInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPipelinePostRequestInner)

	if err != nil {
		return err
	}

	*o = PipelinePostRequestInner(varPipelinePostRequestInner)

	return err
}

type NullablePipelinePostRequestInner struct {
	value *PipelinePostRequestInner
	isSet bool
}

func (v NullablePipelinePostRequestInner) Get() *PipelinePostRequestInner {
	return v.value
}

func (v *NullablePipelinePostRequestInner) Set(val *PipelinePostRequestInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelinePostRequestInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelinePostRequestInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelinePostRequestInner(val *PipelinePostRequestInner) *NullablePipelinePostRequestInner {
	return &NullablePipelinePostRequestInner{value: val, isSet: true}
}

func (v NullablePipelinePostRequestInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelinePostRequestInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


